I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 579, in script
    python:
  File "game/script.rpy", line 597, in <module>
    moment_journee
NameError: name 'moment_journee' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 579, in script
    python:
  File "C:\renpy\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 597, in <module>
    moment_journee
NameError: name 'moment_journee' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.0.882
Meiji 1.0
Sun Oct 28 22:58:56 2018
